### PR TITLE
fix: forwardRef from SideNavigationLink component

### LINKED ISSUE #1122: forwardRef error
After upgrading to 1.2.1 the following error occurs:

```
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
```

It looks like it was caused by this change: https://github.com/canonical/react-components/pull/1118.

### PR DESCRIPTION
**Pull request by aaryanporwal**
## Done

- Fixes #1122 
- [WD-14675](https://warthogs.atlassian.net/browse/WD-14675)

### Percy steps

- No visual changes expected

[WD-14675]: https://warthogs.atlassian.net/browse/WD-14675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by huwshimi — CHANGES_REQUESTED** [review]
It looks like most of the changes need to be reverted from the previous PR: https://github.com/canonical/react-components/pull/1118/files as removing the generic types has broken then ability to handle props when passing `component`.

For example when using this with a `Link` from React Router it would give an error for the `to` prop here as it can't infer the props of the `Link` component:

```typescript
<SideNavigationLink label="docs" component={Link} to="/docs" />
```

Unfortunately `forwardRef` does not support components with generic types, so instead  you have to manually pass a ref. We do that in a few places e.g. https://github.com/canonical/react-components/blob/f60d6bc1f2cb62436a3585c7827d89535d209013/src/components/Panel/Panel.tsx#L136

This issue could be caught in the future if we change this test: https://github.com/canonical/react-components/blob/f60d6bc1f2cb62436a3585c7827d89535d209013/src/components/SideNavigation/SideNavigationLink/SideNavigationLink.test.tsx#L34

To:

```typescript
it("can use a custom link component", () => {
  const Link = ({ to }: { to: () => void }) => (
    <button onClick={to}>link</button>
  );
  const label = "Test content";
  render(<SideNavigationLink label={label} component={Link} to={jest.fn()} />);
  expect(screen.getByRole("button", { name: label })).toHaveClass(
    "p-side-navigation__link",
  );
});
```

**Comment by aaryanporwal** [comment]
> It looks like most of the changes need to be reverted from the previous PR: https://github.com/canonical/react-components/pull/1118/files as removing the generic types has broken then ability to handle props when passing `component`.
> 
> For example when using this with a `Link` from React Router it would give an error for the `to` prop here as it can't infer the props of the `Link` component:
> 
> ```ts
> <SideNavigationLink label="docs" component={Link} to="/docs" />
> ```
> 
> Unfortunately `forwardRef` does not support components with generic types, so instead you have to manually pass a ref. We do that in a few places e.g.
> 
> https://github.com/canonical/react-components/blob/f60d6bc1f2cb62436a3585c7827d89535d209013/src/components/Panel/Panel.tsx#L136
> 
> This issue could be caught in the future if we change this test:
> 
> https://github.com/canonical/react-components/blob/f60d6bc1f2cb62436a3585c7827d89535d209013/src/components/SideNavigation/SideNavigationLink/SideNavigationLink.test.tsx#L34
> 
> To:
> 
> ```ts
> it("can use a custom link component", () => {
>   const Link = ({ to }: { to: () => void }) => (
>     <button onClick={to}>link</button>
>   );
>   const label = "Test content";
>   render(<SideNavigationLink label={label} component={Link} to={jest.fn()} />);
>   expect(screen.getByRole("button", { name: label })).toHaveClass(
>     "p-side-navigation__link",
>   );
> });
> ```

Thank you Huw for pointing that out! I've updated the code and the test like you suggested. Can you please take a look again?

File: src/components/SideNavigation/SideNavigationLink/SideNavigationLink.tsx [hunk 1]
```diff
@@ -16,22 +16,30 @@ export type Props<L = LinkDefaultElement> = Omit<
    * @default a
    */
   component?: SideNavigationBaseProps<L>["component"];
+  /**
+   * A ref to pass to the link element.
+   */
+  forwardRef?: React.Ref<HTMLAnchorElement> | null;
```
Comment (huwshimi) [inline src/components/SideNavigation/SideNavigationLink/SideNavigationLink.tsx:22]: The element won't always be an anchor (if someone has passed the `component` prop) so this might need a new generic that could be set to `HTMLAnchorElement` by default.

**Review by huwshimi — COMMENTED** [review]
This change also needs to be reverted https://github.com/canonical/react-components/pull/1118/files#diff-011b080bc51b47c868f250b3a34619b5f41e4c16c8e39a6636ccc719b6da8bd6L40

**Review by huwshimi — APPROVED** [review]
Thanks for this fix!
